# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8080

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        username: vkapp
        password: N(r65%RVx
        url: jdbc:mysql://10.0.145.50:33006/iep?useUnicode=true&amp;characterEncoding=utf-8
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

